<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<PackageId>Our.Umbraco.PostgreSql.Umbraco.Forms</PackageId>
		<Title>Umbraco CMS - Persistence - Umbraco Forms - PostgreSQL</Title>
		<Description>Adds support for Umbraco Forms with PostgreSQL.</Description>
		<PackageTags>umbraco;umbraco-marketplace</PackageTags>
		<StaticWebAssetBasePath>\</StaticWebAssetBasePath>
		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".pack", ""))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="UFDatasource-definition.json" />
		<None Remove="animal-prevaalues.txt" />
		<None Remove="forms-errors.playlist" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="readme.md" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Security.Cryptography.Xml" Version="[10.0.6,10.1.0)" />
		<PackageReference Include="Umbraco.Forms" Version="17.4.7" />
		<PackageReference Include="Umbraco.Forms.Core.Providers" Version="17.4.7" />
		<PackageReference Include="Our.Umbraco.PostgreSql.Umbraco.License" Version="[17.5.0,18.0.0)" />
		<PackageReference Include="Our.Umbraco.PostgreSql" Version="[17.5.0,18.0.0)" />
	</ItemGroup>

</Project>
