<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="readme.md">
      <PackagePath>\</PackagePath>
      <Pack>true</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="Umbraco.Commerce.Persistence" Version="17.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Our.Umbraco.PostgreSql\Our.Umbraco.PostgreSql.pack.csproj" />
  </ItemGroup>

</Project>
