<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<PackageId>Our.Umbraco.PostgreSql.Umbraco.License</PackageId>
		<Title>Umbraco CMS - Persistence - Umbraco License - PostgreSQL</Title>
		<Description>Adds support for Umbraco License with PostgreSQL.</Description>
		<StaticWebAssetBasePath>\</StaticWebAssetBasePath>
		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".pack", ""))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Our.Umbraco.PostgreSql\Our.Umbraco.PostgreSql.pack.csproj" Version="[18.0.0,19.0.0)" />
	</ItemGroup>

</Project>
