// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Umbraco.Cms.Infrastructure.Persistence.EFCore;

#nullable disable

namespace Our.Umbraco.PostgreSql.EFCore.Migrations
{
    [DbContext(typeof(UmbracoDbContext))]
    [Migration("20260830123109_AddNoOpMirgation")]
    partial class AddNoOpMirgation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("umbracoOpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("umbracoOpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("umbracoOpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("umbracoOpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.AccessDto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createDate");

                    b.Property<int>("LoginNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("loginNodeId");

                    b.Property<int>("NoAccessNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("noAccessNodeId");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("nodeId");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateDate");

                    b.HasKey("Id")
                        .HasName("PK_umbracoAccess");

                    b.HasIndex("LoginNodeId");

                    b.HasIndex("NoAccessNodeId");

                    b.HasIndex("NodeId")
                        .IsUnique()
                        .HasDatabaseName("IX_umbracoAccess_nodeId");

                    b.ToTable("umbracoAccess", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.AccessRuleDto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessId")
                        .HasColumnType("uuid")
                        .HasColumnName("accessId");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createDate");

                    b.Property<string>("RuleType")
                        .HasColumnType("text")
                        .HasColumnName("ruleType");

                    b.Property<string>("RuleValue")
                        .HasColumnType("text")
                        .HasColumnName("ruleValue");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateDate");

                    b.HasKey("Id")
                        .HasName("PK_umbracoAccessRule");

                    b.HasIndex("AccessId");

                    b.HasIndex("RuleValue", "RuleType", "AccessId")
                        .IsUnique()
                        .HasDatabaseName("IX_umbracoAccessRule");

                    b.ToTable("umbracoAccessRule", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.AuditEntryDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedDetails")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("affectedDetails");

                    b.Property<int>("AffectedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("affectedUserId");

                    b.Property<Guid?>("AffectedUserKey")
                        .HasColumnType("uuid")
                        .HasColumnName("affectedUserKey");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eventDateUtc");

                    b.Property<string>("EventDetails")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("eventDetails");

                    b.Property<string>("EventType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("eventType");

                    b.Property<string>("PerformingDetails")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("performingDetails");

                    b.Property<string>("PerformingIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("performingIp");

                    b.Property<int>("PerformingUserId")
                        .HasColumnType("integer")
                        .HasColumnName("performingUserId");

                    b.Property<Guid?>("PerformingUserKey")
                        .HasColumnType("uuid")
                        .HasColumnName("performingUserKey");

                    b.HasKey("Id");

                    b.ToTable("umbracoAudit", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.CacheInstructionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstructionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("instructionCount");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jsonInstruction");

                    b.Property<string>("OriginIdentity")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("originated");

                    b.Property<DateTime>("UtcStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utcStamp");

                    b.HasKey("Id");

                    b.ToTable("umbracoCacheInstruction", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.ConsentDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("action");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Context")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createDate");

                    b.Property<bool>("Current")
                        .HasColumnType("boolean")
                        .HasColumnName("current");

                    b.Property<string>("Source")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("umbracoConsent", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.ContentType2ContentTypeDto", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentContentTypeId");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer")
                        .HasColumnName("childContentTypeId");

                    b.HasKey("ParentId", "ChildId")
                        .HasName("PK_cmsContentType2ContentType");

                    b.HasIndex("ChildId");

                    b.ToTable("cmsContentType2ContentType", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.ContentTypeAllowedContentTypeDto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    b.Property<int>("AllowedId")
                        .HasColumnType("integer")
                        .HasColumnName("AllowedId");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("SortOrder");

                    b.HasKey("Id", "AllowedId")
                        .HasName("PK_cmsContentTypeAllowedContentType");

                    b.ToTable("cmsContentTypeAllowedContentType", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.ContentTypeDto", b =>
                {
                    b.Property<int>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrimaryKey"));

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<bool>("AllowAtRoot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allowAtRoot");

                    b.Property<bool>("AllowedInLibrary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allowedInLibrary");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsElement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isElement");

                    b.Property<Guid?>("ListView")
                        .HasColumnType("uuid")
                        .HasColumnName("listView");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("nodeId");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail");

                    b.Property<int>("Variations")
                        .HasColumnType("integer")
                        .HasColumnName("variations");

                    b.HasKey("PrimaryKey");

                    b.HasIndex("Icon")
                        .HasDatabaseName("IX_cmsContentType_icon");

                    b.HasIndex("NodeId")
                        .IsUnique()
                        .HasDatabaseName("IX_cmsContentType");

                    b.ToTable("cmsContentType", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.ContentTypeTemplateDto", b =>
                {
                    b.Property<int>("ContentTypeNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("contentTypeNodeId");

                    b.Property<int>("TemplateNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("templateNodeId");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDefault");

                    b.HasKey("ContentTypeNodeId", "TemplateNodeId")
                        .HasName("PK_cmsDocumentType");

                    b.ToTable("cmsDocumentType", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.ContentVersionCleanupPolicyDto", b =>
                {
                    b.Property<int>("ContentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("contentTypeId");

                    b.Property<int?>("KeepAllVersionsNewerThanDays")
                        .HasColumnType("integer")
                        .HasColumnName("keepAllVersionsNewerThanDays");

                    b.Property<int?>("KeepLatestVersionPerDayForDays")
                        .HasColumnType("integer")
                        .HasColumnName("keepLatestVersionPerDayForDays");

                    b.Property<bool>("PreventCleanup")
                        .HasColumnType("boolean")
                        .HasColumnName("preventCleanup");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("ContentTypeId")
                        .HasName("PK_umbracoContentVersionCleanupPolicy");

                    b.ToTable("umbracoContentVersionCleanupPolicy", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DataTypeDto", b =>
                {
                    b.Property<int>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("nodeId");

                    b.Property<string>("Configuration")
                        .HasColumnType("text")
                        .HasColumnName("config");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dbType");

                    b.Property<string>("EditorAlias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("propertyEditorAlias");

                    b.Property<string>("EditorUiAlias")
                        .HasColumnType("text")
                        .HasColumnName("propertyEditorUiAlias");

                    b.HasKey("NodeId");

                    b.ToTable("umbracoDataType", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DictionaryDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("key");

                    b.Property<Guid?>("Parent")
                        .HasColumnType("uuid")
                        .HasColumnName("parent");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_cmsDictionary_key");

                    b.HasIndex("Parent")
                        .HasDatabaseName("IX_cmsDictionary_Parent");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("IX_cmsDictionary_id");

                    b.ToTable("cmsDictionary", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DistributedJobDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("IsRunning");

                    b.Property<DateTime>("LastAttemptedRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastAttemptedRun");

                    b.Property<DateTime>("LastRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastRun");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<long>("Period")
                        .HasColumnType("bigint")
                        .HasColumnName("period");

                    b.HasKey("Id");

                    b.ToTable("umbracoDistributedJob", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DomainDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefaultLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("domainDefaultLanguage");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domainName");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<int?>("RootStructureId")
                        .HasColumnType("integer")
                        .HasColumnName("domainRootStructureID");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("umbracoDomain", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.KeyValueDto", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("umbracoKeyValue", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LanguageDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CultureName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("languageCultureName");

                    b.Property<int?>("FallbackLanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("fallbackLanguageId");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDefaultVariantLang");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mandatory");

                    b.Property<string>("IsoCode")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("languageISOCode");

                    b.Property<Guid>("LanguageKey")
                        .HasColumnType("uuid")
                        .HasColumnName("languageKey");

                    b.HasKey("Id");

                    b.HasIndex("FallbackLanguageId");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.HasIndex("LanguageKey")
                        .IsUnique();

                    b.ToTable("umbracoLanguage", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LanguageTextDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("languageId");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId");

                    b.HasIndex("LanguageId", "UniqueId")
                        .IsUnique()
                        .HasDatabaseName("IX_cmsLanguageText_languageId");

                    b.ToTable("cmsLanguageText", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LastSyncedDto", b =>
                {
                    b.Property<string>("MachineId")
                        .HasColumnType("text")
                        .HasColumnName("machineId");

                    b.Property<DateTime>("LastSyncedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastSyncedDate");

                    b.Property<int?>("LastSyncedExternalId")
                        .HasColumnType("integer");

                    b.Property<int?>("LastSyncedInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("lastSyncedInternalId");

                    b.HasKey("MachineId");

                    b.ToTable("umbracoLastSynced", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LogDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("logComment");

                    b.Property<DateTime>("Datestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Datestamp");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entityType");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("logHeader");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("NodeId");

                    b.Property<string>("Parameters")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("parameters");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("IX_umbracoLog");

                    b.HasIndex("UserId");

                    b.HasIndex("Datestamp", "Header")
                        .HasDatabaseName("IX_umbracoLog_datestamp_logheader");

                    b.HasIndex("Datestamp", "UserId", "NodeId")
                        .HasDatabaseName("IX_umbracoLog_datestamp");

                    b.ToTable("umbracoLog", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LongRunningOperationDto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createDate");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirationDate");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateDate");

                    b.HasKey("Id")
                        .HasName("PK_umbracoLongRunningOperation");

                    b.ToTable("umbracoLongRunningOperation", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.MemberPropertyTypeDto", b =>
                {
                    b.Property<int>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pk");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrimaryKey"));

                    b.Property<bool>("CanEdit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("memberCanEdit");

                    b.Property<bool>("IsSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isSensitive");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer")
                        .HasColumnName("NodeId");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("propertytypeId");

                    b.Property<bool>("ViewOnProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("viewOnProfile");

                    b.HasKey("PrimaryKey");

                    b.HasIndex("PropertyTypeId")
                        .IsUnique();

                    b.ToTable("cmsMemberType", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NodeId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createDate");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid?>("NodeObjectType")
                        .HasColumnType("uuid")
                        .HasColumnName("nodeObjectType");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentId");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("path");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<bool>("Trashed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("trashed");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("uniqueId");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("nodeUser");

                    b.HasKey("NodeId");

                    b.HasIndex("Path")
                        .HasDatabaseName("IX_umbracoNode_Path");

                    b.HasIndex("Trashed")
                        .HasDatabaseName("IX_umbracoNode_Trashed");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("IX_umbracoNode_UniqueId");

                    b.HasIndex("NodeObjectType", "Trashed")
                        .HasDatabaseName("IX_umbracoNode_ObjectType");

                    b.HasIndex("ParentId", "NodeObjectType")
                        .HasDatabaseName("IX_umbracoNode_parentId_nodeObjectType");

                    b.HasIndex("NodeObjectType", "Trashed", "SortOrder", "NodeId")
                        .HasDatabaseName("IX_umbracoNode_ObjectType_trashed_sorted");

                    b.HasIndex("Level", "ParentId", "SortOrder", "NodeObjectType", "Trashed")
                        .HasDatabaseName("IX_umbracoNode_Level");

                    b.ToTable("umbracoNode", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.PropertyTypeDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("Alias");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("contentTypeId");

                    b.Property<int>("DataTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("dataTypeId");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Description");

                    b.Property<bool>("LabelOnTop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("labelOnTop");

                    b.Property<bool>("Mandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mandatory");

                    b.Property<string>("MandatoryMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mandatoryMessage");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int?>("PropertyTypeGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("propertyTypeGroupId");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sortOrder");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("UniqueId");

                    b.Property<string>("ValidationRegExp")
                        .HasColumnType("text")
                        .HasColumnName("validationRegExp");

                    b.Property<string>("ValidationRegExpMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("validationRegExpMessage");

                    b.Property<int>("Variations")
                        .HasColumnType("integer")
                        .HasColumnName("variations");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .HasDatabaseName("IX_cmsPropertyTypeAlias");

                    b.HasIndex("DataTypeId");

                    b.HasIndex("PropertyTypeGroupId");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("IX_cmsPropertyTypeUniqueID");

                    b.ToTable("cmsPropertyType", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.PropertyTypeGroupDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<int>("ContentTypeNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("contenttypeNodeId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortorder");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("type");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("uniqueID");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("IX_cmsPropertyTypeGroupUniqueID");

                    b.ToTable("cmsPropertyTypeGroup", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.RedirectUrlDto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentKey")
                        .HasColumnType("uuid")
                        .HasColumnName("contentKey");

                    b.Property<DateTime>("CreateDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createDateUtc");

                    b.Property<string>("Culture")
                        .HasColumnType("text")
                        .HasColumnName("culture");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("UrlHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("urlHash");

                    b.HasKey("Id")
                        .HasName("PK_umbracoRedirectUrl");

                    b.HasIndex("ContentKey");

                    b.HasIndex("CreateDateUtc")
                        .HasDatabaseName("IX_umbracoRedirectUrl_culture_hash");

                    b.HasIndex("UrlHash", "ContentKey", "Culture", "CreateDateUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_umbracoRedirectUrl");

                    b.ToTable("umbracoRedirectUrl", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.RelationDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer")
                        .HasColumnName("childId");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentId");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer")
                        .HasColumnName("relType");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("RelationType");

                    b.HasIndex("ParentId", "ChildId", "RelationType")
                        .IsUnique()
                        .HasDatabaseName("IX_umbracoRelation_parentChildType");

                    b.ToTable("umbracoRelation", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.RelationTypeDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias");

                    b.Property<Guid?>("ChildObjectType")
                        .HasColumnType("uuid")
                        .HasColumnName("childObjectType");

                    b.Property<bool>("Dual")
                        .HasColumnType("boolean")
                        .HasColumnName("dual");

                    b.Property<bool>("IsDependency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDependency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentObjectType")
                        .HasColumnType("uuid")
                        .HasColumnName("parentObjectType");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("typeUniqueId");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique()
                        .HasDatabaseName("IX_umbracoRelationType_alias");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_umbracoRelationType_name");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("IX_umbracoRelationType_UniqueId");

                    b.ToTable("umbracoRelationType", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createDate");

                    b.Property<bool>("Disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("userDisabled");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userEmail");

                    b.Property<DateTime?>("EmailConfirmedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emailConfirmedDate");

                    b.Property<int?>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failedLoginAttempts");

                    b.Property<DateTime?>("InvitedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invitedDate");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LastLockoutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastLockoutDate");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastLoginDate");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastPasswordChangeDate");

                    b.Property<string>("Login")
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)")
                        .HasColumnName("userLogin");

                    b.Property<bool>("NoConsole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("userNoConsole");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("userPassword");

                    b.Property<string>("PasswordConfig")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passwordConfig");

                    b.Property<string>("SecurityStampToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("securityStampToken");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updateDate");

                    b.Property<string>("UserLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("userLanguage");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userName");

                    b.HasKey("Id")
                        .HasName("PK_user");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_umbracoUser_userKey");

                    b.HasIndex("Login");

                    b.ToTable("umbracoUser", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.Webhook2ContentTypeKeysDto", b =>
                {
                    b.Property<int>("WebhookId")
                        .HasColumnType("integer")
                        .HasColumnName("webhookId");

                    b.Property<Guid>("ContentTypeKey")
                        .HasColumnType("uuid")
                        .HasColumnName("entityKey");

                    b.HasKey("WebhookId", "ContentTypeKey")
                        .HasName("PK_webhookEntityKey2Webhook");

                    b.ToTable("umbracoWebhook2ContentTypeKeys", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.Webhook2EventsDto", b =>
                {
                    b.Property<int>("WebhookId")
                        .HasColumnType("integer")
                        .HasColumnName("webhookId");

                    b.Property<string>("Event")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event");

                    b.HasKey("WebhookId", "Event")
                        .HasName("PK_webhookEvent2WebhookDto");

                    b.ToTable("umbracoWebhook2Events", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.Webhook2HeadersDto", b =>
                {
                    b.Property<int>("WebhookId")
                        .HasColumnType("integer")
                        .HasColumnName("webhookId");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("Key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WebhookId", "Key")
                        .HasName("PK_headers2WebhookDto");

                    b.ToTable("umbracoWebhook2Headers", (string)null);
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.WebhookDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("umbracoWebhook", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.AccessDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", null)
                        .WithMany()
                        .HasForeignKey("LoginNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_umbracoAccess_umbracoNode_id1");

                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", null)
                        .WithMany()
                        .HasForeignKey("NoAccessNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_umbracoAccess_umbracoNode_id2");

                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_umbracoAccess_umbracoNode_id");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.AccessRuleDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.AccessDto", "Access")
                        .WithMany("Rules")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.ContentType2ContentTypeDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", "ChildNode")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_cmsContentType2ContentType_umbracoNode_child");

                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", "ParentNode")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_cmsContentType2ContentType_umbracoNode_parent");

                    b.Navigation("ChildNode");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.ContentTypeDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", "NodeDto")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_cmsContentType_umbracoNode");

                    b.Navigation("NodeDto");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DataTypeDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", "NodeDto")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_umbracoDataType_umbracoNode");

                    b.Navigation("NodeDto");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DictionaryDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DictionaryDto", "ParentEntry")
                        .WithMany()
                        .HasForeignKey("Parent")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentEntry");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LanguageDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LanguageDto", "FallbackLanguage")
                        .WithMany()
                        .HasForeignKey("FallbackLanguageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FallbackLanguage");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LanguageTextDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LanguageDto", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DictionaryDto", "DictionaryEntry")
                        .WithMany("LanguageText")
                        .HasForeignKey("UniqueId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryEntry");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.LogDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.UserDto", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.MemberPropertyTypeDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.PropertyTypeDto", "PropertyTypeDto")
                        .WithOne("MemberPropertyTypeDto")
                        .HasForeignKey("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.MemberPropertyTypeDto", "PropertyTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_cmsMemberType_cmsPropertyType");

                    b.Navigation("PropertyTypeDto");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.PropertyTypeDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DataTypeDto", "DataTypeDto")
                        .WithMany()
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_cmsPropertyType_umbracoDataType");

                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.PropertyTypeGroupDto", "PropertyTypeGroupDto")
                        .WithMany("PropertyTypeDtos")
                        .HasForeignKey("PropertyTypeGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_cmsPropertyType_cmsPropertyTypeGroup");

                    b.Navigation("DataTypeDto");

                    b.Navigation("PropertyTypeGroupDto");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.RedirectUrlDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", null)
                        .WithMany()
                        .HasForeignKey("ContentKey")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.RelationDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", "ChildNode")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_umbracoRelation_umbracoNode1");

                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.NodeDto", "ParentNode")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_umbracoRelation_umbracoNode");

                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.RelationTypeDto", "RelationTypeDto")
                        .WithMany()
                        .HasForeignKey("RelationType")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildNode");

                    b.Navigation("ParentNode");

                    b.Navigation("RelationTypeDto");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.Webhook2ContentTypeKeysDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.WebhookDto", "Webhook")
                        .WithMany("Webhook2ContentTypeKeys")
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.Webhook2EventsDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.WebhookDto", "Webhook")
                        .WithMany("Webhook2Events")
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.Webhook2HeadersDto", b =>
                {
                    b.HasOne("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.WebhookDto", "Webhook")
                        .WithMany("Webhook2Headers")
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.AccessDto", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.DictionaryDto", b =>
                {
                    b.Navigation("LanguageText");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.PropertyTypeDto", b =>
                {
                    b.Navigation("MemberPropertyTypeDto");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.PropertyTypeGroupDto", b =>
                {
                    b.Navigation("PropertyTypeDtos");
                });

            modelBuilder.Entity("Umbraco.Cms.Infrastructure.Persistence.Dtos.EFCore.WebhookDto", b =>
                {
                    b.Navigation("Webhook2ContentTypeKeys");

                    b.Navigation("Webhook2Events");

                    b.Navigation("Webhook2Headers");
                });
#pragma warning restore 612, 618
        }
    }
}
